wrapper_name: GATv2Wrapper
agent_name: Agent
game_mode: matrix
train_params:
    device: cuda:0
    epochs: 1 ## epoch for trainings
    splits: 1
    episodes: 5000 ## times to play
    batch_size: 512
    max_steps:  ## step to play, None means play until the game over.
    render_every: 
    render_delay: False
    log_every: 20
    save_every: 20
optimizer_params:
    opt: adam
    lr: 0.001
    weight_decay: 0.0001
    lookahead: False
    opt_scheduler: none
    amsgrad: True
    opt_decay_step: 1
    milestones: [5, 10, 15, 20, 25]
    gamma: 0.995
model_params:
    in_channels: 1
    out_channels: 1
    heads: 3
    model_name: gatv2
    model_type: gnn
    version: lr0.5
    dropout: 0.2
    negative_slope: 0.2
    parameters_path: ./Models/Parameters/
    bias: True
    add_self_loop: True
    positional_embedding: True
    img_size: [20, 10]
    patch_size: [2 ,2]
    embed_dim: 32
    layers: 3
    pooling: set2set
    mode: fully_connected

