wrapper_name: GATv2Wrapper
agent_name: Agent
train_params:
    device: cuda:0
    epochs: 10 ## epoch for trainings
    episodes: 2000 ## times to play
    train_every: 5 ## training interval
    batch_size: 64
    max_steps:  ## step to play, None means play until the game over.
    render_every: 20
    render_delay: False
    log_every: 20
    save_every: 20
optimizer_params:
    opt: radam
    lr: 0.01
    weight_decay: 0.0001
    lookahead: True
    opt_scheduler: multistep
    milestones: [25]
    gamma: 0.2
model_params:
    in_channels: 1
    out_channels: 1
    heads: 3
    model_name: gatv2
    model_type: gnn
    dropout: 0.2
    negative_slope: 0.2
    parameters_path: ./Models/Parameters/
    bias: True
    add_self_loop: True
    positional_embedding: True
    img_size: [20, 10]
    patch_size: [2 ,2]
    embed_dim: 32
    layers: 3
    pooling: set2set

